version: "2"
linters:
  enable:
  - gocyclo
  - misspell
  - revive
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
